version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: "TFA"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "123456"
    ports:
        - "5432:5432" 
    networks:
      - custom_network
    volumes:
        - postgres-data:/var/lib/postgresql/data 
    

  uidb:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: "ozen@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
        - "5050:80"
    networks:
      - custom_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin


networks:
  custom_network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:  