networks:
  default:
    name: 'tfa'

volumes:
  tfa-pg:
  tfa-logs:

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: "TFA"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "123456"
    ports:
        - "5432:5432"
    volumes:
        - tfa-pg:/var/lib/postgresql/data 
    
  opensearch:
    image: 'opensearchproject/opensearch:2.10.0'
    container_name: 'tfa-os'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: true
    volumes:
      - tfa-logs:/usr/share/opensearch/data
    
  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: tfa-osd
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://tfa-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch

#  uidb:
#    image: dpage/pgadmin4
#    container_name: pgadmin4
#    restart: always
#    environment:
#        PGADMIN_DEFAULT_EMAIL: "ozen@gmail.com"
#        PGADMIN_DEFAULT_PASSWORD: "123456"
#    ports:
#        - "5050:80"
#    networks:
#      - custom_network
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin


